### ISSUE TITLE
No such file or directory: 'riscv64-unknown-elf-gcc'

### ISSUE THREAD

**Issue by dotornot** [defconfurs/dcfurs-badge-dc28#1]
I've tried everything and can't get the code to compile:
```
dotornot@Elwood:~/Downloads/dcfurs-badge-dc28$ sudo ./make.py build
[sudo] password for dotornot: 
BIOS [bios.bin] building...
   Compiling [trap.c]
Traceback (most recent call last):
  File "./make.py", line 522, in <module>
    main()
  File "./make.py", line 494, in main
    buildrom('bios')
  File "./make.py", line 285, in buildrom
    compile(objfile, srcfile)
  File "./make.py", line 163, in compile
    subprocess.check_call([gcc] + CFLAGS + ['-c', '-o', target, source], stderr=subprocess.STDOUT)
  File "/usr/lib/python3.8/subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'riscv64-unknown-elf-gcc'
```

Brand new install of Ubuntu.
riscv-gnu-toolchain fully installed with multilib. I'm genuinely stuck.

**Comment by dotornot** [comment]
I fixed the issue by adding the full path in make.py:
`    else:
        gcc           = '/opt/riscv/bin/riscv64-unknown-elf-gcc'
        objcopy       = '/opt/riscv/bin/riscv64-unknown-elf-objcopy' `
