### ISSUE TITLE
'nano.specs': No such file or directory

### ISSUE THREAD

**Issue by sonicer105** [defconfurs/dcfurs-badge-dc28#4]
Getting the following error when I try to compile with `./make.py`:

```
BIOS [bios.bin] building...
   Compiling [bios_printf.c]
riscv64-unknown-elf-gcc: fatal error: cannot read spec file 'nano.specs': No such file or directory
compilation terminated.
Traceback (most recent call last):
  File "./make.py", line 522, in <module>
    main()
  File "./make.py", line 494, in main
    buildrom('bios')
  File "./make.py", line 285, in buildrom
    compile(objfile, srcfile)
  File "./make.py", line 163, in compile
    subprocess.check_call([gcc] + CFLAGS + ['-c', '-o', target, source], stderr=subprocess.STDOUT)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['riscv64-unknown-elf-gcc', '-Os', '-march=rv32i', '-mabi=ilp32', '-I', '/opt/dcfurs-badge-dc28', '-ffunction-sections', '-fdata-sections', '--specs=nano.specs', '-D', '_POSIX_TIMERS', '-D', '_POSIX_MONOTONIC_CLOCK=200112L', '-c', '-o', '/opt/dcfurs-badge-dc28/bios/bios_printf.o', '/opt/dcfurs-badge-dc28/bios/bios_printf.c']' returned non-zero exit status 1.
```

Using Ubuntu 20.04 LTS with the `gcc-riscv64-unknown-elf` and `dfu-util` from the standard ubuntu repo

**Comment by phasenoisepon** [comment]
Try compiling the risv compiler with multilib support

**Comment by sonicer105** [comment]
Had to compile the risc toolchain from source. Works now.
